### ISSUE TITLE
build.bat error

### ISSUE THREAD

**Issue by tzTZtzTZqwq** [Fluffy-Frontier/FluffySTG#4773]
## Issue Summary

build.bat error

## Reproduction:

Using vendored Node v20.13.0
:: Juke Build version 0.8.1
:: Skipping 'cutter' (condition unmet)
:: Skipping 'yarn' (up to date)
:: Skipping 'tgui' (up to date)
=> Starting 'icon-cutter'
=> Target 'icon-cutter' failed in 0.004s, unhandled exception:
Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:761:9)
    at C:\Users\FluffySTG-master\FluffySTG-master\tools\build\juke\index.js:4407:50
    at new Promise (<anonymous>)
    at Object.exec (C:\Users\FluffySTG-master\FluffySTG-master\tools\build\juke\index.js:4400:10)
    at Target.executes (file:///C:/Users/FluffySTG-master/FluffySTG-master/tools/build/build.js:180:16)
    at Worker.process (C:\Users\FluffySTG-master\FluffySTG-master\tools\build\juke\index.js:5000:27) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}
=> Target 'dm' failed
=> Target 'build' failed

**Comment by AnywayFarus** [comment]
Honestly, we don't have that problem. Try digging around in the build, maybe update node js (or better yet, reinstall the build). 
Basically, he just couldn't open the application he needed.
